### ISSUE TITLE
Performence issus when making 6 deeps

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#21]
Me again~

I need to make a 6 deep JSON a bit like this 3deeps sample:

```
{
  "PAYS": [
    {
      "NAME": "ANDORRE",
      "REGIONS": [
        {
          "NAME": "ANDORRE default regions",
          "DEPARTEMENTS": [
            {
              "NAME": "ANDORRE default departements"
            }
          ]
        }
      ]
    },
    {
      "NAME": "ARENTINA",
      "REGIONS": [
        {
          "NAME": "regions 1",
          "DEPARTEMENTS": [
            {
              "NAME": "departements A"
            },
            {
              "NAME": "departements B"
            }
          ]
        }
      ]
    },
    {
      "NAME": "KOREA",
      "REGIONS": [
        {
          "NAME": "regions 1",
          "DEPARTEMENTS": [
            {
              "NAME": "departements A"
            }
          ]
        },
        {
          "NAME": "regions 2",
          "DEPARTEMENTS": [
            {
              "NAME": "departements C"
            }
          ]
        }
      ]
    }
  ]
}
```

I'm using the following job, but it take 2:30 hours to process, is there a quicker way to do it ?

```
+----------+--------------------------+-------------------------------+
|   PAYS   |         REGIONS          |         DEPARTEMENTS          |
+----------+--------------------------+-------------------------------+
| ANDORRE  | ANDORRE default regions  | ANDORRE default departements  |
| ARENTINA | regions 1                | departements A                |
| ARENTINA | regions 1                | departements B                |
| KOREA    | regions 1                | departements A                |
| KOREA    | regions 2                | departements C                |
+----------+--------------------------+-------------------------------+
```

![image](https://user-images.githubusercontent.com/6142277/37978330-17a9a1dc-31e6-11e8-8cab-524a4c8995c9.png)

The tricky points are:
- the deep are array without explicit index (so I can't target a json path)
- the NAME (in fact NAME1 to NAME6) are composite keys ( there is 2 different `regions 1`,  in two pays)
- I'm processing 36k lines 

I'm wondering if the Iterate way is the good one...

**Comment by jlolling** [comment]
Hi blag

yeas of course! I know such scenarios very well. We had such scenarios with database selects and when we had calculated the necessary queries it was terrible.
Thats because I have introduced the foreign key assignment to the tJSONDocOutput.
The idea is to read every level only once and not per parent node.
The first flow have to got over the first level nodes.
Mark the column which is the key s key in the schema.
The components provides a list of the keys as SQL-comma separated list.
In your scenario you do not need this.
You have to have in your files for the second and following levels columns which references to the parent level.
You choose such this column per level and tell the component to use it a foreign key relation.
![tug_20180215_gvl_core_webservices](https://user-images.githubusercontent.com/8038781/37989308-5bf0ff76-3203-11e8-96a5-2253ca0256c6.png)

**Comment by blag001** [comment]
I'm definitely going mad on this one...
The FK mode can't find my key and blow-up every time.

I think the point is really about making a composite key that tell the `region1` in `paysA>region1>depA1` is not the same than `paysB>region1>depB1`

The job 
![image](https://user-images.githubusercontent.com/6142277/38031691-1a1112fa-329c-11e8-97e0-c7e920cf5a44.png)
the error 
![image](https://user-images.githubusercontent.com/6142277/38031703-289e06fc-329c-11e8-8c8f-c4dfdf84b300.png)

Create Doc
![image](https://user-images.githubusercontent.com/6142277/38032233-691714f2-329d-11e8-9f13-25fe47c13735.png)

csv schema of pays 
![image](https://user-images.githubusercontent.com/6142277/38031748-45b06474-329c-11e8-97dc-eebd72b8ce06.png)

The first node 
![image](https://user-images.githubusercontent.com/6142277/38032182-488580c0-329d-11e8-96c6-86448e3c1fca.png)


2nd CSV
![image](https://user-images.githubusercontent.com/6142277/38032012-e6cd7388-329c-11e8-90cb-8601a0e6d4d1.png)

region node 
![image](https://user-images.githubusercontent.com/6142277/38032423-e348d79c-329d-11e8-8022-49c27f6cdc4e.png)

last CSV
![image](https://user-images.githubusercontent.com/6142277/38032450-f4e7187e-329d-11e8-9a83-489479b4126c.png)

And the belonging docOutput
![image](https://user-images.githubusercontent.com/6142277/38032483-0fcac852-329e-11e8-9408-6f8ed3833610.png)

-----

If I disable the 3rd CSV/output (departments level), I'll have 1st and 2nd level as I want, but the 3rd and deeper level either go on error on `CODCOURT2=00` or use `CODCOURT2` as a unique key and put everything in the last occurrence of the key (aka all my default departments for the world end up in the Zimbabwe default region...)

![image](https://user-images.githubusercontent.com/6142277/38032765-b2475c80-329e-11e8-88f7-fe4135b312b0.png)

**Comment by jlolling** [comment]
I agree with you, the limitation to only one key field is not comfortable. Mostly we found easy ways to build one combined key. I use the component tHashRow to do that (the result of a cooperation with some friends): https://github.com/jlolling/talendcomp_tHashRow
We have developed this component for the purpose of building keys for a Data Vault.

**Comment by jlolling** [comment]
I you have further more problems with it we can do a skype session and I take a look at your jobs and we fix everything together.

**Comment by blag001** [comment]
Thanks again Jan, 
As I've got your confirmation tJSONDoc was not able to handle native composite key, I was able to try other things and find how to do it.

I'm working on a Plateform version, so I used `tGenKey` to make a composite key as a single column instead of your `tHashRow`. My fear was having to ship this pk_key in the generated JSON dump, but it even seem to work without! 

I'm now able to make my 2h30 job in less than 120s, quite a nice change~ 

I'll add some screen-shot tomorrow.

**Comment by jlolling** [comment]
I know very well whats your pain. We have created web services with these components and those web services have to provide a multi-object response, e.g. 1000 products at once in one response.
It was terrible - we had minutes instead of seconds as response time. With the foreign key solution we was able to reduce the response time from 2-3 minutes to 1-2 seconds.

I have thought about combined keys but this what increase the complexity of the component to a not maintainable level.
