### ISSUE TITLE
[tJSONDocInputStream] Trouble with backslashes in json field 

### ISSUE THREAD

**Issue by tchachoua96** [jlolling/talendcomp_tJSONDoc#41]
Hello,

We are facing an issue when one of the fields contains "\\\\". Example : 

{
	"operations": {
		"operation": [
			{
				"date": "2020-07-08T16:45:56",
				"name": "Operation01 \\\\"
			}
		]
	}
}

The component creates a new json in the output but it does delete one backslash . Example : 

"name": "Operation01 \\\".

This generate an error when it is transformed into XML. Can you see how to avoid this issue and be able to generate an XML from the JSON in the previous JSON example ?

We are using Talend 7.3 version. 

Thanks in advance !

**Comment by jlolling** [comment]
I will check that soon.

**Comment by tchachoua96** [comment]
Hello !

any news on the subject ?

Thanks in advance.

Regards,

Taha

**Comment by jlolling** [comment]
I am currently checking that. Sorry, was a busy time these days.

**Comment by jlolling** [comment]
I can confirm the problem if I use tJSONDocInput and read the attribute name.

**Comment by jlolling** [comment]
The problem is caused by the underlaying json library. I am trying to fix that.

**Comment by jlolling** [comment]
It looks like the json content has to be read as String with escape sequences. This means, a json value " \\ " actually mean one \ . This is how the libraries interpret this value. 
I am also a bit surprised and was not aware of it.
https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string

I hope it is clear now. Your experiences are not the result of a failure, it is the way how json works. You have to write "Operation01 \\\\" as json value.
If you want to use a String literal you have to do this: "Operation01 \\\\\\\\". Looks strange but it is correct this way.

**Comment by jlolling** [comment]
I have checked also what result we get if I write a field content with only one backslash and got the expected result of a json with TWO backslashes because the one was escaped internally.
Think about the line breaks. json does not have actually no line breaks within content. To add them you need exactly this mechanism to escape backslashes and a line break appears as \n within the json content and not as "real" line brerak.

**Comment by tchachoua96** [comment]
Thanks for your answer ! 

The problem we have though is when we have a backslash that is immediatly followed by a double quote. The JSON library interprets it as a backslash ("Operation01 \\\\" to "Operation01 \\\") and that's why we lose one backslash (the one at the end because I think it is used by the library to escape the double quote, which is not our case). The double quote is for the json field and it is not an intern double quote. 

Thanks again for your investigation.

**Comment by jlolling** [comment]
NO, thats not why you lose one backslash. It is because the string content in json is actually written like a Java String with escape chars. If you want to have `Operation01 \` that means in your json you have to have:  `"Operation01 \\"`.
It works differently than xml or plain text files containing this text content.
If you do not beliefe me, put a space between the \ and the " and the result will be the same!
